Feat/#74
AegisLenz/AegisLenz-BE pull request #76
Opened 2024-12-05 16:07 UTC by jyjyjy25

## 🔥 Related Issue
- Close #74

## 🏃‍ Task
- attack_detections 모델 재설계
- 공격 발생 시 공격흐름그래프 생성 로직 추가

## 💬 To Reviews 
- 전달사항 작성

## 📄 Reference
- None

## ✅ Check List
- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2024-12-07 04:47 UTC, chae1xxlos requested changes
코드 짜느라 고생하셨어여.. 너무 잘 짜시네요. 더 고생해주세요🥹ㅎㅎㅎ

2024-12-07 04:47 UTC, chae1xxlos commented on models/attack_detection_model.py
> +    attack_graph: str
`attack_graph: Optional[str] = None`

얘도 처리해주는게 좋을듯?

2024-12-07 04:47 UTC, chae1xxlos commented on models/attack_detection_model.py
> +    user_id: str
`user_id: Optional[str] = None`

얘두ㅋㅋㅋㅋ

2024-12-07 04:47 UTC, chae1xxlos commented on models/attack_detection_model.py
>      created_at: datetime
요거 utc 걸어주자

`created_at: datetime = Field(default_factory=datetime.utcnow)`

2024-12-07 04:47 UTC, chae1xxlos commented on repositories/bert_repository.py
>          try:
user_id랑 attack_graph 조건문 달자

```
if not user_id or not isinstance(user_id, str):
            raise ValueError("Invalid user_id")
        if not attack_graph or not isinstance(attack_graph, str):
            raise ValueError("Invalid attack_graph")
```

2024-12-07 04:47 UTC, chae1xxlos commented on repositories/bert_repository.py
>                  created_at=datetime.now(timezone(timedelta(hours=9))).replace(tzinfo=None)
`created_at=datetime.utcnow()`

2024-12-07 04:47 UTC, chae1xxlos commented on repositories/bert_repository.py
>          except Exception as e:
attack_detection 함수 str로 받아와서 디버깅 추가하는게 나을듯ㅜ

```
await self.mongodb_engine.save(attack_detection)
        return str(attack_detection.id)
    except ValueError as ve:
        raise HTTPException(status_code=400, detail=str(ve))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to save attack detection: {e}")
```

2024-12-07 04:47 UTC, chae1xxlos commented on services/bert_service.py
로깅이랑 예외 처리 세분화 좀 했어여^^

```
async def process_after_detection(self, user_id: str, attack_info: dict):
        # 1. 자산 업데이트
        try:
            await self.asset_service.update_asset(user_id)
            logger.debug("asset updated successfully.")
        except Exception as e:
            logger.error(f"Error updating asset for user_id {user_id}: {e}")
            raise HTTPException(status_code=500, detail="Failed to update user assets.")

        # 2. 보고서 & 추천 질문 & 최소권한정책 & 공격 흐름그래프 생성
        try:
            report = await self._create_report(attack_info)
            logger.debug(f"Generated report: {report}")

            recommend_prompt, recommend_questions = await self._create_recommend_questions(attack_info, report)
            logger.debug(f"Generated recommended questions: {recommend_questions}")

            least_privilege_policy = await self.policy_service.generate_least_privilege_policy(user_id)
            logger.debug(f"Generated least privilege policy: {least_privilege_policy}")

            attack_graph = await self._create_attack_graph(attack_info)
            logger.debug(f"Generated attack graph: {attack_graph}")

            logger.debug("report, recommend questions, least privilege policy, attack_graph generated successfully.")
        except Exception as e:
            logger.error(f"Error during report or question generation: {e}")
            raise HTTPException(status_code=500, detail="Failed to generate report, questions, or policies.")
```

2024-12-09 16:06 UTC, jyjyjy25 commented on models/attack_detection_model.py
> +    attack_graph: str
얘는 무조건 생성되는 얘라 옵션처리 안했으요 ~

2024-12-09 16:06 UTC, jyjyjy25 commented on models/attack_detection_model.py
> +    user_id: str
얘는 무조건 추가되는 값이라 옵션처리 안했으요 22~

2024-12-10 05:52 UTC, merged