Feat/#81
AegisLenz/AegisLenz-BE pull request #82
Opened 2024-12-07 08:42 UTC by chae1xxlos

## 🔥 Related Issue
- Close #81 

## 🏃‍ Task
- 헬퍼 메소드를 추가해서 에러 처리 및 재시도 로직 통합
- 키값 상수로 분리해서 관리하도록 로직 구현
- 재시도 횟수 딜레이를 설정 가능한 상수로 분리
- 각 메소드 내부 operation 함수 사용해서 구조화

## 💬 To Reviews 
- 꼼꼼하게 확인 부탁드려요 지윤상

## 📄 Reference
- None

## ✅ Check List
- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2024-12-09 05:45 UTC, jyjyjy25 requested changes
굿굿 좀만 더 수고해보자요 :>

2024-12-09 05:45 UTC, jyjyjy25 commented on routers/bert_router.py
>          )
last_timestamp가 없을 땐 모든 로그를 가져올 거 같은데 모든 로그를 처리하는게 로직 상 맞나요? 아니면 예외처리가 필요할 듯 !

2024-12-09 05:45 UTC, jyjyjy25 commented on routers/bert_router.py
> +                                        "mitreAttackTechnique": str(prediction),
str(normalized_prediction)로 들어가야하지 않남?

2024-12-09 05:45 UTC, jyjyjy25 commented on routers/bert_router.py
> +                                    es.index(index="cloudtrail-logs", id=log_id, body=attack_document)
공격으로 탐지된 로그 저장하는 index 이름 좀 더 명확하게 attack 등 키워드 넣어서 다시 명명해주세요 ~

2024-12-09 05:45 UTC, jyjyjy25 commented on routers/bert_router.py
> +                                    user_id = log.get("userIdentity", {}).get("arn", "unknown_user")
process_after_detection()에 인자로 들어가는 user_id는 로그에 있는 id가 아니라 우리 솔루션에 가입한 유저의 id라 일단 "1"로 넣어주시면 될 듯합니다 :>

2024-12-09 16:02 UTC, jyjyjy25 requested changes
굿굿 !

2024-12-10 02:54 UTC, chae1xxlos commented on routers/bert_router.py
> +attack_index_name = "cloudtrail-attack-logs"
너 백엔드 서버 .env에 추가했으니 확인바람~~

2024-12-10 05:51 UTC, jyjyjy25 approved these changes
LGTM ~~

2024-12-10 15:18 UTC, jyjyjy25 reviewed
예외처리가 확실하시군요 ~ 좋은 밤 되시길 :>

2024-12-11 08:48 UTC, merged