Feat/#86
AegisLenz/AegisLenz-BE pull request #88
Opened 2024-12-10 17:42 UTC by jyjyjy25

## 🔥 Related Issue
- #86

## 🏃‍ Task
- 공격 보고서 관련 API 구현

## 💬 To Reviews 
- 전달사항 작성

## 📄 Reference
- None

## ✅ Check List
- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2024-12-11 16:18 UTC, chae1xxlos requested changes
와 코드 진심 개잘짰는데? 진심 하나하나 보면서 감탄함;; 찐으로

2024-12-11 16:18 UTC, chae1xxlos commented on models/attack_detection_model.py
> +    selected_field: list
`selected_field: list[str]`

타입 지정해주면 좋을듯!

2024-12-11 16:18 UTC, chae1xxlos commented on services/report_service.py
> +        reports = await self.report_repository.find_reports_by_user_id(user_id)
트라이 넣어주자

```
try:
        reports = await self.report_repository.find_reports_by_user_id(user_id)
        if not reports:
            logger.warning(f"No reports found for user_id={user_id}")
            return GetAllReportResponseSchema(report_ids=[])
```

2024-12-11 16:18 UTC, chae1xxlos commented on services/report_service.py
> +        report_ids = [str(report.id) for report in reports]
요기 리포트 갖고 오는거 갯수 로그로 기록해서 디버깅 하는걸로!

```
report_ids = [str(report.id) for report in reports]
        logger.info(f"Fetched {len(report_ids)} reports for user_id={user_id}")
        return GetAllReportResponseSchema(report_ids=report_ids)
    except Exception as e:
        logger.error(f"Error fetching reports for user_id={user_id}: {str(e)}")
        raise HTTPException(status_code=500, detail="Failed to fetch reports.")
```

2024-12-11 16:18 UTC, chae1xxlos commented on schemas/report_schema.py
> +    selected_field: list
`selected_field: list[str]`

2024-12-12 04:56 UTC, jyjyjy25 commented
@chae1xxlos 반영완. 확인바람 ~~

2024-12-12 12:29 UTC, merged