Feat/#75
AegisLenz/AegisLenz-BE pull request #90
Opened 2024-12-11 11:20 UTC by jyjyjy25

## 🔥 Related Issue
- Close #75

## 🏃‍ Task
- ES 쿼리 결과 처리
- 꼬리질문 대강 처리
- 프롬프트 요약 타이틀 생성 로직 구현

## 💬 To Reviews 
- 전달사항 작성

## 📄 Reference
- None

## ✅ Check List
- [ ]  PR의 제목은 팀 내 규칙을 준수하여 알맞게 작성하였는가?
- [ ]  Merge 하는 브랜치가 올바른가? (`main` branch에 실수로 PR 생성 금지)
- [ ]  팀의 코딩 컨벤션을 준수하는가?
- [ ]  PR과 관련없는 변경사항이 들어가지는 않았는가?
- [ ]  내 코드에 대한 자기 검토가 되었는가?
- [ ]  Reviewers, Assignees, Lables, Project, Milestone은 적절하게 선택하였는가?
- [ ]  관련한 issue를 닫아야 하는지 점검해보고 적용했는가?

2024-12-11 16:08 UTC, chae1xxlos requested changes
로직 구현이 코드 모르는 사람이 봐도 알정도로 잘 되어있네여.. 짱짱

2024-12-11 16:08 UTC, chae1xxlos commented on services/prompt_service.py
> +
예외 처리 웬만하면 다 빼줄라 했는데 너무 중요하다 이건

```
else:
            raise HTTPException(status_code=500, detail="Unknown persona type.")

    except Exception as e:
        logger.error(f"Error processing prompt for session_id: {prompt_session_id}, user_id: {user_id}, error: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to process prompt.")
```

2024-12-11 16:08 UTC, chae1xxlos commented on schemas/prompt_schema.py
>          json_schema_extra = {
이거 따로 빼ㅡㅡ

2024-12-11 16:08 UTC, chae1xxlos commented on schemas/prompt_schema.py
> +    title: Optional[str]
초기화 안된거 예외처리 ㄱㄱ

```
title: Optional[str] = None
    chats: List[GetPromptContentsSchema] = Field(default_factory=list)
    report: Optional[str] = None
    attack_graph: Optional[str] = None
    least_privilege_policy: Optional[Dict[str, Dict[str, List[Any]]]] = Field(default_factory=dict)
    init_recommend_questions: List[str] = Field(default_factory=list)
```

2024-12-12 08:15 UTC, jyjyjy25 commented on repositories/prompt_repository.py
> +    async def create_prompt(self, user_id: str, attack_detection_id: Optional[str] = None, recommend_history: Optional[List[Dict]] = None,
처음 프롬프트 생성하는 함수라 일단 create, update 동일하게 주고, 나중에 채팅 추가될때마다 updated_at은 추가된 시간으로 업데이트 됩니덩~ 또한, 프롬프트에서 마지막 대화한 날짜 나타내야하기 때문에 해당 시간 관련 필드 필요! 

나머지는 반영함~

2024-12-12 12:25 UTC, chae1xxlos approved these changes
굳굳!!

2024-12-12 13:20 UTC, merged